### ISSUE TITLE
epub3-validator: Failed to load com.adobe.epubcheck.xml.XMLValidator$SilencingErrorListener

### ISSUE THREAD

**Issue by josteinaj** [daisy/pipeline#537]
### Steps to Reproduce

1. Start v1.12 of the engine: `docker run --network=host --publish 8181:8181 --env PIPELINE2_WS_AUTHENTICATION=false --rm -it daisyorg/pipeline-assembly:v1.12.0`
2. start the latest version of the webui: `docker run --network=host --publish 9000:9000 --rm -it daisyorg/pipeline-webui`
3. Open the webui at http://localhost:9000/
4. Try validating an EPUB using the EPUB 3 Validator script (I use the test EPUB from the nordic migrator project, but any will probably do: [C00000.epub](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/raw/master/src/test/resources/C00000.epub))

### Environment
* Docker host operating system: Ubuntu 18.04
* Docker version: 18.09.5
* DAISY Pipeline 2 version: 1.12.0
* Interface: WebUI

### Logs
[job-1.log](https://github.com/daisy/pipeline/files/3083679/job-1.log)

**Comment by josteinaj** [comment]
XMLValidator$SilencingErrorListener was removed from epubcheck February 24th in w3c/epubcheck@cfca41b8aef9ea938acd1d9265fd789ddb5cb8b9. I don't know if that change has made it into DP2 v1.12 or not. I don't see any reference to SilencingErrorListener from other places.

**Comment by bertfrees** [comment]
OK I was able to reproduce. The XProcSpec test works fine, so I assume this is a new JAR dependency that I haven't added to the assembly.

**Comment by bertfrees** [comment]
We use epubcheck 4.1.1 by the way.

**Comment by bertfrees** [comment]
- org.idpf:epubcheck:jar:4.1.1:runtime
  - net.sf.saxon:Saxon-HE:jar:9.8.0-8:runtime
  - org.apache.commons:commons-compress:jar:1.18:runtime
  - org.daisy.libs:jing:jar:20151127.0.0:runtime
  - **org.w3c.css:sac:jar:1.3:runtime**
  - **com.twelvemonkeys.imageio:imageio-jpeg:jar:3.4.1:runtime**
    - **com.twelvemonkeys.imageio:imageio-core:jar:3.4.1:runtime**
    - **com.twelvemonkeys.imageio:imageio-metadata:jar:3.4.1:runtime**
    - **com.twelvemonkeys.common:common-lang:jar:3.4.1:runtime**
    - **com.twelvemonkeys.common:common-io:jar:3.4.1:runtime**
    - **com.twelvemonkeys.common:common-image:jar:3.4.1:runtime**
  - org.codehaus.jackson:jackson-core-asl:jar:1.9.12:runtime
  - org.codehaus.jackson:jackson-mapper-asl:jar:1.9.12:runtime

These are the dependencies and the bold ones we currently don't include. But I don't think this is the issue. The error message suggests that it is a Saxon + OSGi issue. It looks like Saxon wants to dynamically load a class but OSGi's classloader mechanism prevents that. @rdeltour does that make sense?

```
Caused by: java.lang.IllegalArgumentException: Cannot use com.adobe.epubcheck.xml.XMLValidator$SilencingErrorListener as the value of http://saxon.sf.net/feature/stylesheetErrorListener. Failed to load com.adobe.epubcheck.xml.XMLValidator$SilencingErrorListener
	at net.sf.saxon.Configuration.instantiateClassName(Configuration.java:4746) ~[na:na]
	at net.sf.saxon.Configuration.setConfigurationProperty(Configuration.java:4620) ~[na:na]
	at net.sf.saxon.s9api.Processor.setConfigurationProperty(Processor.java:352) ~[na:na]
	at net.sf.saxon.jaxp.SaxonTransformerFactory.setAttribute(SaxonTransformerFactory.java:306) ~[na:na]
	at com.adobe.epubcheck.xml.XMLValidator$ExtendedSaxonSchemaReaderFactory.initTransformerFactory(XMLValidator.java:201)
	at ...
```

**Comment by rdeltour** [comment]
> The error message suggests that it is a Saxon + OSGi issue. It looks like Saxon wants to dynamically load a class but OSGi's classloader mechanism prevents that. @rdeltour does that make sense?

Yes, it seems to be the issue there.

With EPUBCheck 4.2.0 around the corner, where this specific Saxon config have been removed as @josteinaj correctly pointed out, maybe we can try to update EPUBCheck rather than trying to fix this?

**Comment by bertfrees** [comment]
Yes makes sense.

**Comment by josteinaj** [comment]
Ok. I'll have to wait with a new release of the nordic migrator until this is fixed.

What kind of timeframe are we talking about? EPUBCheck 4.2.0 within a few weeks? And then a new patch release of DP2 within a few weeks after that?

**Comment by bertfrees** [comment]
If the Pipeline release only requires a new version of EPUBCheck, it can be done immediately when EPUBCheck is released.

**Comment by rdeltour** [comment]
EPUBCheck v4.2.0 will be available later today 😊

**Comment by josteinaj** [comment]
I tried simply replacing the epubcheck 4.1.1 JAR with the 4.2.0 JAR (hoping for a bit of luck), but it results in a `java.lang.NoClassDefFoundError: Could not initialize class com.adobe.epubcheck.ocf.OCFChecker`. So I guess some changes are needed to `epubcheck-adapter`.

**Comment by bertfrees** [comment]
If you update the version in the modules-bom to 4.2.0 it seems to work. At least I can run the unit tests of epubcheck-adapter and epub3-validator.

**Comment by bertfrees** [comment]
@josteinaj I was able to simply update the version in the assembly and tested epub3-validator with the C00000 book. See https://github.com/daisy/pipeline-assembly/compare/epubcheck-4.2.0? Can you try it?

**Comment by NPavie** [comment]
I managed to make the validation work with the new 4.2.0-rc epubcheck available in the maven central repository.
(I'll mark the modifications in a commit linked to this issue)

**Comment by rdeltour** [comment]
@NPavie Cool! Note that [v4.2.0 final is also on Maven](https://search.maven.org/artifact/org.w3c/epubcheck/4.2.0/jar) now :-)

**Comment by NPavie** [comment]
I missed the release on the epubcheck repo :) some minor changes to make on the files and should be good to go !

**Comment by josteinaj** [comment]
@bertfrees after fixing the Dockerfile in https://github.com/daisy/pipeline-assembly/issues/166 I could test your change to the assembly pom, and the epub validator script works again now. Thanks!

So, next up I suppose there will be a v1.12.1 bugfix release of the system at some point?

**Comment by bertfrees** [comment]
Great. I'll make the release on Monday.
